# Generated by Django 5.1.4 on 2025-01-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaykarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'managed': True},
        ),
    ]
