# Generated by Django 5.1.4 on 2025-01-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaykarApp', '0002_alter_teams_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='responsible_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BaykarApp.parts'),
        ),
    ]
