# Generated by Django 5.1.4 on 2025-01-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaykarApp', '0003_teams_responsible_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='BaykarApp.parts'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='BaykarApp.teams'),
        ),
    ]
