# Generated by Django 5.1.4 on 2025-01-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaykarApp', '0004_alter_production_created_at_alter_production_part_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={},
        ),
    ]
